#!/bin/bash
# Mostly generated by Claude

# =============================================================================
# Jellyfin Login Script — Direct DB approach
# Authenticates a user against SQLite, generates an API token, and injects
# an HTML script that sets localStorage.jellyfin_credentials for the client.
#
# ENV VARS (required):
#   SERVER_ADDRESS  — full base URL visible to the browser, e.g. http://jellyfin.local
#
# ENV VARS (optional):
#   DB_PATH         — path to jellyfin.db       (default: /config/data/jellyfin.db)
#   CONFIG_PATH     — path to Jellyfin config dir (default: /config/config)
#
# ARGS:
#   $1              — username
#   $2              — device name (optional, defaults to "API Login")
#   $3              — app name   (optional, defaults to "Atoile")
#
# Auto-resolved (no env var needed):
#   SERVER_ID       — read from /config/data/device.txt
#   SERVER_NAME     — read from <ServerName> in $CONFIG_PATH/system.xml
# =============================================================================

DB_PATH="${DB_PATH:-/config/data/jellyfin.db}"
CONFIG_PATH="${CONFIG_PATH:-/config/config}"

DEVICE_TXT="/config/data/device.txt"
SYSTEM_XML="${CONFIG_PATH}/system.xml"

USERNAME="${1:-}"
DEVICE_NAME="${2:-API Login}"
APP_NAME="${3:-Atoile}"

set -euo pipefail

if [[ -z "${SERVER_ADDRESS:-}" ]]; then
  echo "[ERROR] SERVER_ADDRESS env var is required (e.g. http://jellyfin.local)"
  exit 1
fi

if [[ -z "$USERNAME" ]]; then
  echo "[ERROR] Usage: $0 <username> [device_name] [app_name]"
  exit 1
fi

if [[ ! -f "$DB_PATH" ]]; then
  echo "[ERROR] Database not found at $DB_PATH"
  exit 1
fi

# --- Read server identity files -----------------------------------------------

if [[ ! -f "$DEVICE_TXT" ]]; then
  echo "[ERROR] device.txt not found at $DEVICE_TXT"
  exit 1
fi
SERVER_ID=$(sed 's/^\xef\xbb\xbf//' "$DEVICE_TXT" | tr -d '[:space:]')

if [[ ! -f "$SYSTEM_XML" ]]; then
  echo "[ERROR] system.xml not found at $SYSTEM_XML"
  exit 1
fi
SERVER_NAME=$(python3 -c "
import xml.etree.ElementTree as ET
tree = ET.parse('${SYSTEM_XML}')
name = tree.getroot().findtext('ServerName')
if not name:
    raise SystemExit('[ERROR] <ServerName> not found in system.xml')
print(name)
")

echo "[login] Server: ${SERVER_NAME} (${SERVER_ID})"

command -v sqlite3 >/dev/null 2>&1 || {
  echo "[setup] Installing sqlite3..."
  apt-get update -qq
  apt-get install -y -qq sqlite3 python3
}

echo "[login] Authenticating user: $USERNAME"

USER_DATA=$(sqlite3 "$DB_PATH" <<SQL
SELECT Id FROM Users WHERE Username = '${USERNAME}' LIMIT 1;
SQL
)

if [[ -z "$USER_DATA" ]]; then
  echo "[ERROR] User '$USERNAME' not found"
  exit 1
fi

USER_ID=$(echo "$USER_DATA" | cut -d'|' -f1)
echo "[login] User found: $USER_ID"

ADMIN_TOKEN=$(python3 -c "import secrets; print(secrets.token_hex(16))")
DEVICE_ID="atoile-login-$(python3 -c 'import uuid; print(uuid.uuid4())')"
NOW=$(date -u '+%Y-%m-%d %H:%M:%S.0000000')

echo "[login] Generated token: ${ADMIN_TOKEN:0:8}..."
echo "[login] Device ID: $DEVICE_ID"

echo "[login] Recording device in database..."

sqlite3 "$DB_PATH" <<SQL
INSERT INTO Devices (
  UserId,
  AccessToken,
  AppName,
  AppVersion,
  DeviceName,
  DeviceId,
  IsActive,
  DateCreated,
  DateModified,
  DateLastActivity
) VALUES (
  '${USER_ID}',
  '${ADMIN_TOKEN}',
  '${APP_NAME}',
  '1.0.0',
  '${DEVICE_NAME}',
  '${DEVICE_ID}',
  1,
  '${NOW}',
  '${NOW}',
  '${NOW}'
);
SQL

echo "[login] Device recorded"

# Build the jellyfin_credentials JSON and emit a single-line <script> tag.
# python3 handles all quoting/escaping so the shell never touches the JSON directly.
HTML_SCRIPT=$(python3 - <<PYEOF
import json, time

creds = {
    "Servers": [{
        "DateLastAccessed":   int(time.time() * 1000),
        "LastConnectionMode": 2,
        "ManualAddress":      "${SERVER_ADDRESS}",
        "manualAddressOnly":  True,
        "Name":               "${SERVER_NAME}",
        "Id":                 "${SERVER_ID}",
        "LocalAddress":       "${SERVER_ADDRESS}",
        "AccessToken":        "${ADMIN_TOKEN}",
        "UserId":             "${USER_ID}",
    }]
}

echo "[DEBUG] ADMIN_TOKEN=$ADMIN_TOKEN"
echo "[DEBUG] USER_ID=$USER_ID"
echo "[DEBUG] SERVER_ADDRESS=$SERVER_ADDRESS"

payload = json.dumps(creds, separators=(',', ':'))
# Escape </script> sequences that could break the inline script context
payload = payload.replace('</', r'<\/')

script = (
    "<script>"
    "(function(){{"
    "try{{"
    "localStorage.setItem('jellyfin_credentials','{payload}');"
    "console.log('[jellyfin-login] credentials written for user {user}, token {token}...');"
    "}}catch(e){{console.error('[jellyfin-login] localStorage write failed',e);}}"
    "}})();"
    "</script>"
).format(
    payload=payload,
    user="${USER_ID}",
    token="${ADMIN_TOKEN}"[:8],
)

print(script)
PYEOF
)

echo "$HTML_SCRIPT"