#!/bin/bash
# Mostly generated by Claude

# =============================================================================
# Jellyfin Setup Script — direct DB approach
# Configures Jellyfin by writing config files and SQLite DB directly.
# No API calls, no wizard, no fragile HTTP endpoints.
#
# ENV VARS (required):
#   SERVER_NAME     — display name for the server
#   BASE_URL        — base path, e.g. /jellyfin
#   PROXY_IP        — IP of the reverse proxy to trust
#   CONFIG_PATH     — path to Jellyfin config dir, e.g. /config/config
#   DB_PATH         — path to jellyfin.db, e.g. /config/data/jellyfin.db
#   users           — JSON array of KeyEntity objects from Atoile
#                     [{"appId":"...","user":{"username":"..."},"key":"..."},...]
# =============================================================================

SERVER_NAME="Atoile Jellyfin"
PROXY_IP="http://localhost"
CONFIG_PATH="/config/config"
export DB_PATH="/config/data/jellyfin.db"

set -euo pipefail

# ─── Dependencies ─────────────────────────────────────────────────────────────

echo "[setup] Installing dependencies..."
apt-get update -qq
apt-get install -y -qq python3
echo "[setup] Dependencies ready."

if [[ ! -f "$DB_PATH" ]]; then
  echo "[ERROR] Database not found at $DB_PATH — has Jellyfin started at least once?"
  exit 1
fi

if [[ -z "${users:-}" ]]; then
  echo "[ERROR] 'users' env var is not set or empty."
  exit 1
fi

echo "[setup] Starting Jellyfin direct setup..."

# ─── 1. Write system.xml ──────────────────────────────────────────────────────

echo "[setup] Writing system.xml..."
cat > "$CONFIG_PATH/system.xml" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<ServerConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <LogFileRetentionDays>3</LogFileRetentionDays>
  <IsStartupWizardCompleted>true</IsStartupWizardCompleted>
  <EnableMetrics>false</EnableMetrics>
  <EnableNormalizedItemByNameIds>true</EnableNormalizedItemByNameIds>
  <IsPortAuthorized>true</IsPortAuthorized>
  <QuickConnectAvailable>false</QuickConnectAvailable>
  <EnableCaseSensitiveItemIds>true</EnableCaseSensitiveItemIds>
  <PreferredMetadataLanguage>en</PreferredMetadataLanguage>
  <MetadataCountryCode>FR</MetadataCountryCode>
  <ServerName>${SERVER_NAME}</ServerName>
  <UICulture>en-US</UICulture>
  <EnableLegacyAuthorization>true</EnableLegacyAuthorization>
  <CorsHosts>
    <string>*</string>
  </CorsHosts>
  <PluginRepositories>
    <RepositoryInfo>
      <n>Jellyfin Stable</n>
      <Url>https://repo.jellyfin.org/files/plugin/manifest.json</Url>
      <Enabled>true</Enabled>
    </RepositoryInfo>
  </PluginRepositories>
  <ActivityLogRetentionDays>30</ActivityLogRetentionDays>
</ServerConfiguration>
EOF

# ─── 2. Write network.xml ─────────────────────────────────────────────────────

echo "[setup] Writing network.xml..."
cat > "$CONFIG_PATH/network.xml" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<NetworkConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <EnableHttps>false</EnableHttps>
  <RequireHttps>false</RequireHttps>
  <InternalHttpPort>8096</InternalHttpPort>
  <InternalHttpsPort>8920</InternalHttpsPort>
  <PublicHttpPort>8096</PublicHttpPort>
  <PublicHttpsPort>8920</PublicHttpsPort>
  <AutoDiscovery>false</AutoDiscovery>
  <EnableIPv4>true</EnableIPv4>
  <EnableIPv6>false</EnableIPv6>
  <EnableRemoteAccess>true</EnableRemoteAccess>
  <KnownProxies>
    <string>${PROXY_IP}</string>
  </KnownProxies>
  <IgnoreVirtualInterfaces>true</IgnoreVirtualInterfaces>
  <VirtualInterfaceNames>
    <string>veth</string>
  </VirtualInterfaceNames>
  <EnablePublishedServerUriByRequest>true</EnablePublishedServerUriByRequest>
  <IsRemoteIPFilterBlacklist>false</IsRemoteIPFilterBlacklist>
</NetworkConfiguration>
EOF

# ─── 3. Create users from KeyEntity JSON (with admin permissions) ─────────────

echo "[setup] Processing users from 'users' env var..."

python3 - <<PYEOF
import json, os, hashlib, binascii, secrets, uuid, sqlite3, sys
from datetime import datetime, timezone

db_path = os.environ["DB_PATH"]
users_json = os.environ["users"]
now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S.0000000")

try:
    entries = json.loads(users_json)
except json.JSONDecodeError as e:
    print(f"[ERROR] Failed to parse 'users' env var as JSON: {e}", file=sys.stderr)
    sys.exit(1)

def pbkdf2_hash(key: str) -> str:
    """Hash key in Jellyfin's PBKDF2-SHA512 format."""
    iterations = 210000
    salt = secrets.token_bytes(32)
    dk = hashlib.pbkdf2_hmac("sha512", key.encode(), salt, iterations)
    salt_hex = binascii.hexlify(salt).decode().upper()
    dk_hex   = binascii.hexlify(dk).decode().upper()
    return f"\$PBKDF2-SHA512\$iterations={iterations}\${salt_hex}\${dk_hex}"

con = sqlite3.connect(db_path)
cur = con.cursor()

created = 0
skipped = 0

for entry in entries:
    username = entry["user"]["username"]
    key      = entry["key"]

    # Skip if already exists
    cur.execute("SELECT COUNT(*) FROM Users WHERE Username = ?", (username,))
    if cur.fetchone()[0] > 0:
        print(f"[WARNING] User '{username}' already exists — skipping.")
        skipped += 1
        continue

    user_id       = str(uuid.uuid4()).upper()
    password_hash = pbkdf2_hash(key)
    device_id     = f"atoile-setup-{uuid.uuid4()}"

    cur.execute("SELECT COALESCE(MAX(InternalId), 0) + 1 FROM Users")
    internal_id = cur.fetchone()[0]

    # Insert user
    cur.execute("""
        INSERT INTO Users (
            Id, Username, Password,
            AuthenticationProviderId, PasswordResetProviderId,
            MustUpdatePassword, InvalidLoginAttemptCount, LoginAttemptsBeforeLockout,
            MaxActiveSessions, EnableAutoLogin, EnableLocalPassword,
            EnableNextEpisodeAutoPlay, EnableUserPreferenceAccess,
            DisplayCollectionsView, DisplayMissingEpisodes, HidePlayedInLatest,
            RememberAudioSelections, RememberSubtitleSelections,
            PlayDefaultAudioTrack, SubtitleMode, SyncPlayAccess,
            InternalId, LastActivityDate, LastLoginDate, RowVersion
        ) VALUES (
            ?, ?, ?,
            'Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider',
            'Jellyfin.Server.Implementations.Users.DefaultPasswordResetProvider',
            0, 0, NULL, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
            ?, ?, ?, 1
        )
    """, (user_id, username, password_hash, internal_id, now, now))

    # Required preference rows (Kind 0-3 must exist for every user)
    for kind in range(4):
        cur.execute(
            "INSERT INTO Preferences (Kind, UserId, Value, RowVersion) VALUES (?, ?, '', 0)",
            (kind, user_id)
        )

    cur.execute(
        "INSERT OR IGNORE INTO Permissions (UserId, Kind, Value, RowVersion) VALUES (?, 0, 1, 0)",
        (user_id,)
    )

    con.commit()
    print(f"[setup] Created admin user '{username}' (ID: {user_id})")
    created += 1

con.close()
print(f"[setup] Done — {created} user(s) created (admin perms granted), {skipped} skipped.")
PYEOF

# ─── 4. Summary ───────────────────────────────────────────────────────────────

echo ""
echo "[setup] All done. Restart Jellyfin to apply config changes."