services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - /atoile/apps/jellyfin/config:/config
      - /atoile/apps/jellyfin/cache:/cache
      # Storage volumes loaded into Atoile
      # %storage_volumes%
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=%proxied_url% # E.G http://atoile.local/jellyfin/
    extra_hosts:
      - 'host.docker.internal:host-gateway'